name: Bot Lif 24/7

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 */6 * * *'

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: pip install -r requirements.txt
      - name: Run Bot
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }} # Guna token bot LIFT
        run: python lift_bot.py # TUKAR SINI: Mesti panggil fail kod lif!
